// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCjn7FO4Epca6zw8tlvo19N1wy25kBJXs0',
    appId: '1:776420540497:web:80117bca5944402d01f870',
    messagingSenderId: '776420540497',
    projectId: 'flutteracademind',
    authDomain: 'flutteracademind.firebaseapp.com',
    databaseURL: 'https://flutteracademind-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'flutteracademind.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCXIDjzGBOx_4s3CYkE1WBXSe9RNbOKxK0',
    appId: '1:776420540497:android:545f4cc0e84236d801f870',
    messagingSenderId: '776420540497',
    projectId: 'flutteracademind',
    databaseURL: 'https://flutteracademind-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'flutteracademind.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBFw02Clf-NReXwr_1TXOhAptUS8YOgrQg',
    appId: '1:776420540497:ios:392a719276f1326201f870',
    messagingSenderId: '776420540497',
    projectId: 'flutteracademind',
    databaseURL: 'https://flutteracademind-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'flutteracademind.appspot.com',
    iosClientId: '776420540497-741amkafp1bks1pu3cidm3h0hpeoc6ta.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBFw02Clf-NReXwr_1TXOhAptUS8YOgrQg',
    appId: '1:776420540497:ios:b857a20294ae0ab801f870',
    messagingSenderId: '776420540497',
    projectId: 'flutteracademind',
    databaseURL: 'https://flutteracademind-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'flutteracademind.appspot.com',
    iosClientId: '776420540497-i4pm6m0nl8kumph537mm4jr7bjcav41r.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp.RunnerTests',
  );
}
